### ISSUE TITLE
Extension file not found when use with Java

### ISSUE THREAD

**Issue by y2kenny** [pubref/rules_protobuf#122] opened 2017-09-11 18:29 UTC
Got this error:
```
ERROR: error loading package '': Extension file not found. Unable to load package for '@org_pubref_rules_protobuf//java/rules.bzl:rules.bzl': BUILD file not found on package path
```

... even though this is specified in the `WORKSPACE`:
```
git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.8.0",
)

load("@org_pubref_rules_protobuf//java/rules.bzl", "java_proto_repositories")
java_proto_repositories()
```

**Comment by pcj** [comment] 2017-09-11 18:32
@y2kenny What does your BUILD file look like and how are you invoking bazel (like `bazel build :my_target`).

**Comment by y2kenny** [comment] 2017-09-11 18:39
In the folder containing the proto file (`src/main/proto/dex_api.proto`) I have `src/main/proto/BUILD`:
```
package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")

java_proto_library(
    name = "java_dex_proto_lib",
    protos = ["dex_api.proto"],
    with_grpc = True,
    verbose = 1,
)
```

At the root `BUILD`, I have (added `"//src/main/proto:java_dex_proto_lib"` to the deps):
```
load("//tools/bzl:plugin.bzl", "gerrit_plugin")

gerrit_plugin(
    name = "oauth",
    srcs = glob(["src/main/java/**/*.java"]),
    manifest_entries = [
        "Gerrit-PluginName: gerrit-oauth-provider",
        "Gerrit-Module: com.googlesource.gerrit.plugins.oauth.Module",
        "Gerrit-HttpModule: com.googlesource.gerrit.plugins.oauth.HttpModule",
        "Gerrit-InitStep: com.googlesource.gerrit.plugins.oauth.InitOAuth",
        "Implementation-Title: Gerrit OAuth authentication provider",
        "Implementation-URL: https://github.com/davido/gerrit-oauth-provider",
    ],
    resources = glob(["src/main/resources/**/*"]),
    deps = [
        "@commons_codec//jar:neverlink",
        "@scribe//jar",
	"//src/main/proto:java_dex_proto_lib",
    ],
)
```

I didn't quite get to build yet.  I was just try to see if the bazel files are ok by running `bazel query //src/...`

**Comment by pcj** [comment] 2017-09-11 20:40
Would be curious about build output.  Query seems to request/require more things internally for bazel than expected.  Not that this is not a bug, just a different priority.

**Comment by y2kenny** [comment] 2017-09-11 20:43
It's entirely possible that I missed something (I am very new to this whole Bazel thing.)  I am just not quite sure where to try.  The error message made it sound like the git repository was not pulled but I really have no idea in terms of how to move forward to figure this one out.

**Comment by y2kenny** [comment] 2017-09-11 20:47
Actually I just noticed the error message `error loading package ''` appear to say that there's an empty string/name/package (the '')?

**Comment by pcj** [comment] 2017-09-11 20:59
So what happens when you `$ bazel build src/main/proto:java_dex_proto_lib`?

**Comment by y2kenny** [comment] 2017-09-11 21:03
I got the same error.

BUT, I think I found the problem.  So I just debug line by line by commenting out all the new additions and here's what I find.  I get error with this:
load("@org_pubref_rules_protobuf//java**/**rules.bzl", "java_proto_repositories")

but not with this:
load("@org_pubref_rules_protobuf//java**:**rules.bzl", "java_proto_repositories")

Looks like it's working now.  Sorry about this.

**Comment by pcj** [comment] 2017-09-11 21:07
Yes the [label syntax](https://docs.bazel.build/versions/master/build-ref.html#labels) takes some getting used to 😃 

I'll close this if resolved but feel free to re-open if needed.

**Closed by pcj** 2017-09-11 21:07 UTC
